/**
 * Maizzle base config (local / development builds).
 *
 * `config.production.js` layers the inlining, purging and minification on top.
 * Both share everything here, so what you preview locally is structurally the
 * file that ships.
 */

import {
	color,
	fontFamily,
	fontSize,
	fontWeight,
	tracking,
	layout,
	budget
} from './lib/tokens.mjs';
import { localeContext, availableLocales } from './lib/locales.mjs';

/** Absolute HTTPS origin for locked brand chrome. Never a relative path. */
const SITE_ORIGIN = process.env.EMAIL_SITE_ORIGIN || 'https://www.golfhomesinternational.com';

export default {
	build: {
		content: ['src/templates/**/*.html'],
		output: {
			path: 'build_local',
			from: ['src/templates']
		}
	},

	components: {
		root: './',
		folders: ['src/components', 'src/layouts'],

		/*
		 * posthtml-component reserves `src` as the attribute naming the component
		 * file, which collides head-on with `<img src>`: `<x-figure src="...jpg">`
		 * is otherwise read as "load a component from that JPEG". Rebinding it
		 * frees `src` to mean what it means in HTML.
		 */
		attribute: 'component-src',

		expressions: {
			/*
			 * A missing prop renders as nothing rather than the literal string
			 * `{local}`. In email a stray placeholder ships to an inbox; failing
			 * quiet and letting the validator catch the empty region is safer.
			 */
			missingLocal: '',
			strictMode: false
		}
	},

	/*
	 * Default values for every component prop.
	 *
	 * These are not cosmetic. posthtml-expressions evaluates `{{ }}` as real
	 * JavaScript, so a comparison against a prop that was not passed
	 * (`tone === 'on-green'` where the component was used without `tone`) throws
	 * a ReferenceError. In non-strict mode the whole expression is then
	 * swallowed and renders as an empty string, which silently produces
	 * `color:;` and `bgcolor=""` in the built file: components lose their
	 * colours with no error at build time and no sign until an inbox test.
	 *
	 * Declaring every prop here means it is always defined. A component
	 * attribute overrides it, and posthtml-component resets the scope per
	 * component, so values never leak between siblings.
	 *
	 * Adding a new prop to a component means adding its default here.
	 *
	 * Every default is the empty string, meaning "not provided", and components
	 * resolve their real default with `prop === '' ? fallback : prop`. Two
	 * reasons, both learned the hard way:
	 *
	 *   1. posthtml-component runs JSON.parse over every attribute value, so
	 *      `level="1"` arrives as the NUMBER 1, not the string '1'. A `=== '1'`
	 *      comparison silently never matches, and the component quietly renders
	 *      its fallback branch. Numeric props are therefore compared with `==`.
	 *
	 *   2. That same coercion makes `gap="0"` the number 0, which is falsy, so
	 *      the common `{{ gap || 24 }}` idiom turns a deliberate zero back into
	 *      24px. Checking against '' instead of truthiness keeps zero meaning
	 *      zero.
	 */
	locals: {
		tone: 'default',
		variant: 'body',
		size: '',
		level: '',
		align: '',
		edit: '',
		caption: '',
		href: '',
		src: '',
		alt: '',
		width: '',
		height: '',
		gap: '',
		pt: '',
		pb: ''
	},

	/*
	 * Design tokens, exposed to templates and components as `page.*`.
	 *
	 * These sit at the TOP LEVEL of the config rather than under `locals`, and
	 * that is deliberate. Maizzle builds its expression scope as
	 * `{ ...config.locals, page: config }`, so anything under `locals` is only
	 * reachable bare (`{{ brand.green }}`) while front matter and anything set
	 * in `beforeRender` is only reachable as `page.*`. Putting tokens here means
	 * one consistent namespace everywhere: `page.brand.green`, `page.i18n.dir`,
	 * `page.title`. A bare local would also be shadowed by any component prop
	 * that happened to share its name.
	 *
	 * Components read from here rather than hard-coding values, so
	 * lib/tokens.mjs stays the single source of truth even though the styles
	 * themselves are written inline.
	 */
	brand: {
		green: color.green,
		gold: color.gold,
		white: color.white,
		onGreen: color.onGreen,
		charcoal: color.charcoal,
		border: color.border,
		muted: color.muted
	},

	font: fontFamily,
	weight: fontWeight,
	scale: fontSize,
	track: tracking,
	space: layout,
	limits: budget,

	site: {
		origin: SITE_ORIGIN,
		/*
		 * Brand chrome is hosted statically on the brand domain and generated by
		 * bin/build-assets.mjs. Campaign imagery is different: it goes through
		 * the Sanity CDN via lib/image-url.mjs, format pinned.
		 */
		logoIvory: `${SITE_ORIGIN}/email/logo-ivory@2x.png`,
		logoGreen: `${SITE_ORIGIN}/email/logo-green-on-white@2x.png`,
		logoWidth: 200,
		logoHeight: 45
	},

	/*
	 * Tailwind sits in Maizzle's PostCSS chain unconditionally. This system does
	 * not use it (see docs/01-technical-standard.md: critical CSS is written
	 * inline by the components, and the <style> block is hand-written so the
	 * responsive and dark-mode policy can be read in one screen). Pointing it at
	 * the templates keeps it quiet; with no @tailwind directive in main.css it
	 * emits nothing.
	 */
	css: {
		tailwind: {
			content: ['./src/**/*.html']
		}
	},

	/**
	 * Resolve the locale before the template renders.
	 *
	 * One campaign is one locale. The template declares `locale: es` in front
	 * matter; everything direction- and language-dependent is derived here so a
	 * component never has to ask which language it is in.
	 */
	beforeRender({ config }) {
		const requested = config.locale || 'en';

		try {
			Object.assign(config, localeContext(requested));
		} catch (error) {
			throw new Error(
				`${error.message}\n` +
					`  Template requested locale "${requested}".\n` +
					`  Available: ${availableLocales().join(', ')}`
			);
		}
	},

	/* Readable output locally; production minifies instead. */
	prettify: true
};
